#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/Xresources
sysmodmap=/etc/X11/Xmodmap

# merge in defaults and keymaps

test -f $sysresources    && xrdb -merge  $sysresources
test -f $sysmodmap       && xmodmap      $sysmodmap
test -f "$userresources" && xrdb -merge "$userresources"
test -f "$usermodmap"    && xmodmap     "$usermodmap"

# start some nice programs
eval $(ssh-agent)

test $(which xsetroot)  && xsetroot -solid '#3c3836' &
test $(which gpg-agent) && eval $(gpg-agent --daemon)

xinitcfg="$HOME/.xinitrc"
test -f "$xinitcfg"     && . "$xinitcfg"


if [ $(which slstatus) ]; then
    slstatus &
elif [ $(which dwmstatus) ]; then
    dwmstatus &
fi

/usr/local/bin/dwm 2>.dwm_log
